FROM fedora:latest
ARG WASM_EDGE_VERSION="0.12.1"

# Install the deps for building crun
RUN dnf update -y && dnf install -y make python git gcc automake autoconf libcap-devel \
		systemd-devel yajl-devel libseccomp-devel pkg-config diffutils \
		libgcrypt-devel systemd-devel yajl-devel libseccomp-devel pkg-config \
		go-md2man glibc-static python3-libmount libtool buildah podman which

# Install WasmEdge
RUN curl -sSf -o install.sh https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh
RUN bash ./install.sh -p /usr -v $WASM_EDGE_VERSION
RUN cp -P /usr/lib/libwasmedge* /usr/lib64/

# Install other tools

RUN dnf install -y unzip wget

# Build crun

COPY . /crun
RUN cd /crun \
		&& git config --global --add safe.directory /crun \
		&& git clean -fdx \
		&& ./autogen.sh \
		&& ls -alh \
		&& ./configure CFLAGS='-Wall -Wextra -Werror' --with-wasmedge \
		&& make -j "$(nproc)" \
		&& make install
# Remove the installed crun to make sure the built crun is used
RUN rm -rf /usr/bin/crun \
		&& ln -s /usr/local/bin/crun /usr/bin/crun \
		&& ln -s /usr/local/bin/crun /usr/local/bin/crun-wasm \
		&& ln -s /usr/local/bin/crun /usr/bin/crun-wasm
